apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: app-service
  name: app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: app-service
    spec:
      containers:
        - env:
            - name: MODEL_SERVICE_URL
              value: http://model-service:8081
            - name: PORT
              value: "8080"
          image: ghcr.io/doda25-team15/app:v1.0.6
          name: app-service
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
