apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: model-service
  name: model-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: model-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: model-service
    spec:
      containers:
        - env:
            - name: PORT
              value: "8081"
          image: ghcr.io/doda25-team15/model-service:v1.0.2
          name: model-service
          ports:
            - containerPort: 8081
              protocol: TCP
          volumeMounts:
            - mountPath: /output
              name: volume-cache
      restartPolicy: Always
      volumes:
        - name: volume-cache
          persistentVolumeClaim:
            claimName: volume-cache
