apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.labels.app.name }}-deployment-v1
  labels:
    app: {{ .Values.labels.app.app }}
    component: {{ .Values.labels.app.component }}
    version: v1
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount.app }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app.app }}
      component: {{ .Values.labels.app.component }}
      version: v1
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app.app }}
        component: {{ .Values.labels.app.component }}
        version: v1
    spec:
      containers:
      - name: app
        image: "{{ .Values.image.app.repository }}:{{ .Values.image.app.tag }}"
        imagePullPolicy: {{ .Values.image.app.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.app.port }}
        envFrom:
          - configMapRef:
              name: {{ .Values.configMap.name }}
