{{- if .Values.shadow.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.shadow.name }}-v3
  labels:
    app: {{ .Values.labels.model.app }}
    version: v3
    role: shadow
spec:
  replicas: {{ .Values.shadow.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.labels.model.app }}
      version: v3
      role: shadow
  template:
    metadata:
      labels:
        app: {{ .Values.labels.model.app }}
        version: v3
        role: shadow
    spec:
      containers:
        - name: model
          image: "{{ .Values.shadow.image.repository }}:{{ .Values.shadow.image.tag }}"
          imagePullPolicy: {{ .Values.shadow.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.model.port }}
          envFrom:
            - secretRef:
                name: {{ .Values.secret.name }}
          volumeMounts:
            - name: shadow-output
              mountPath: {{ .Values.volumeMounts.mountPath }}
      volumes:
          - name: shadow-output
            hostPath:
              path: {{ .Values.shadow.volume.hostPath }}
              type: DirectoryOrCreate
{{- end }}
