{{- if .Values.shadow.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.shadow.name }}
  labels:
    app: {{ .Values.labels.model.app }}
    component: model
    role: shadow
    version: v3
spec:
  replicas: {{ .Values.shadow.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.labels.model.app }}
      role: shadow
      version: v3
  template:
    metadata:
      labels:
        app: {{ .Values.labels.model.app }}
        role: shadow
        version: v3
        component: model
    spec:
      containers:
        - name: model
          image: "{{ .Values.shadow.image.repository }}:{{ .Values.shadow.image.tag }}"
          imagePullPolicy: {{ .Values.shadow.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.model.port }}
          envFrom:
            - secretRef:
                name: {{ .Values.secret.name }}
          volumeMounts:
            - name: shadow-output
              mountPath: {{ .Values.volumeMounts.mountPath }}
          volumes:
            - name: shadow-output
              hostPath:
                path: {{ .Values.shadow.volume.hostPath }}
                type: DirectoryOrCreate
{{- end }}
