---
- hosts: "node-*"
  become: yes
  tasks:
    # STEP 18 — Generate Join Command
    - name: Generate kubeadm join command on controller
      shell: kubeadm token create --print-join-command
      register: join_command
      delegate_to: ctrl

    # STEP 19 — Run Join Command
    - name: Check if node is already joined
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: Join node to Kubernetes cluster
      shell: "{{ join_command.stdout }}"
      when: not kubelet_conf.stat.exists
